"""Initial_models

Revision ID: 1932313fcc57
Revises: 
Create Date: 2026-09-18 19:30:22.583400
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1932313fcc57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_org_id'), 'app_user', ['org_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scope_authorized', sa.Boolean(), nullable=False),
    sa.Column('bug_bounty_url', sa.String(length=1024), nullable=True),
    sa.Column('scope_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_company_org_name')
    )
    op.create_index(op.f('ix_company_org_id'), 'company', ['org_id'], unique=False)
    op.create_table('webhook',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('min_severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_org_id'), 'webhook', ['org_id'], unique=False)
    op.create_table('wildcard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('root_domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scope_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'root_domain', name='uq_wildcard_company_domain')
    )
    op.create_index(op.f('ix_wildcard_company_id'), 'wildcard', ['company_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('wildcard_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('scan_mode', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wildcard_id'], ['wildcard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_org_id'), 'schedule', ['org_id'], unique=False)
    op.create_index(op.f('ix_schedule_wildcard_id'), 'schedule', ['wildcard_id'], unique=False)
    op.create_table('scope_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wildcard_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.String(length=1024), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wildcard_id'], ['wildcard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_rule_wildcard_id'), 'scope_rule', ['wildcard_id'], unique=False)
    op.create_table('subdomain',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wildcard_id', sa.UUID(), nullable=False),
    sa.Column('fqdn', sa.String(length=255), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('ip_addresses', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cname_target', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('web_server', sa.String(length=255), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('roi_score', sa.Integer(), nullable=False),
    sa.Column('scope_status', sa.String(length=50), nullable=False),
    sa.Column('security_headers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scanned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['wildcard_id'], ['wildcard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wildcard_id', 'fqdn', name='uq_subdomain_wildcard_fqdn')
    )
    op.create_index(op.f('ix_subdomain_fqdn'), 'subdomain', ['fqdn'], unique=False)
    op.create_index(op.f('ix_subdomain_wildcard_id'), 'subdomain', ['wildcard_id'], unique=False)
    op.create_table('dns_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_record_subdomain_id'), 'dns_record', ['subdomain_id'], unique=False)
    op.create_table('port_service',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('banner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain_id', 'port', 'protocol', name='uq_port_service_sub_port_proto')
    )
    op.create_index(op.f('ix_port_service_subdomain_id'), 'port_service', ['subdomain_id'], unique=False)
    op.create_table('scan_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_job_target_id'), 'scan_job', ['target_id'], unique=False)
    op.create_table('ssl_certificate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('subject_an', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('is_self_signed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain_id')
    )
    op.create_table('url',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('full_url', sa.String(length=2048), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('discovery_method', sa.String(length=50), nullable=True),
    sa.Column('response_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain_id', 'full_url', name='uq_url_subdomain_url')
    )
    op.create_index(op.f('ix_url_subdomain_id'), 'url', ['subdomain_id'], unique=False)
    op.create_table('agent_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('observation', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('action_chosen', sa.String(length=100), nullable=False),
    sa.Column('action_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('education_note', sa.String(), nullable=True),
    sa.Column('used_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decision_scan_job_id'), 'agent_decision', ['scan_job_id'], unique=False)
    op.create_table('tool_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('execution_logs', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_run_scan_job_id'), 'tool_run', ['scan_job_id'], unique=False)
    op.create_table('url_parameter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('param_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id', 'name', name='uq_url_parameter_url_name')
    )
    op.create_index(op.f('ix_url_parameter_url_id'), 'url_parameter', ['url_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('tool_run_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=True),
    sa.Column('discovery_tool', sa.String(length=100), nullable=False),
    sa.Column('matched_at', sa.String(length=2048), nullable=True),
    sa.Column('extracted_results', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('curl_command', sa.String(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_run_id'], ['tool_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_subdomain_id'), 'finding', ['subdomain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_subdomain_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_url_parameter_url_id'), table_name='url_parameter')
    op.drop_table('url_parameter')
    op.drop_index(op.f('ix_tool_run_scan_job_id'), table_name='tool_run')
    op.drop_table('tool_run')
    op.drop_index(op.f('ix_agent_decision_scan_job_id'), table_name='agent_decision')
    op.drop_table('agent_decision')
    op.drop_index(op.f('ix_url_subdomain_id'), table_name='url')
    op.drop_table('url')
    op.drop_table('ssl_certificate')
    op.drop_index(op.f('ix_scan_job_target_id'), table_name='scan_job')
    op.drop_table('scan_job')
    op.drop_index(op.f('ix_port_service_subdomain_id'), table_name='port_service')
    op.drop_table('port_service')
    op.drop_index(op.f('ix_dns_record_subdomain_id'), table_name='dns_record')
    op.drop_table('dns_record')
    op.drop_index(op.f('ix_subdomain_wildcard_id'), table_name='subdomain')
    op.drop_index(op.f('ix_subdomain_fqdn'), table_name='subdomain')
    op.drop_table('subdomain')
    op.drop_index(op.f('ix_scope_rule_wildcard_id'), table_name='scope_rule')
    op.drop_table('scope_rule')
    op.drop_index(op.f('ix_schedule_wildcard_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_org_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_wildcard_company_id'), table_name='wildcard')
    op.drop_table('wildcard')
    op.drop_index(op.f('ix_webhook_org_id'), table_name='webhook')
    op.drop_table('webhook')
    op.drop_index(op.f('ix_company_org_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_app_user_org_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('organization')
    # ### end Alembic commands ###
